### PR TITLE
Dd #90 SSL curl error

### PR DESCRIPTION
**Pull request by ddumitre456**
- [x] Development complete
- [ ] Documentation complete
- [ ] Test case added
- [ ] Release notes updated
- [x] Representative testing complete
- [ ] Full testing complete

Note that we still have an error when compiling the PostgreSQL plugin. For this reason I have removed the respective plugin from the makefiles.

To enable the compilation of the PostgresSQL plugin you have to:

1) Rename `xPackagex` file to `Package` in `mistral_plugins/output/mistral_postgresql` folder

2) Add PostgreSQL back into the `mistral_plugins/Makefile` by removing the comments which disable the PostgresSQL compilation

### CODE REVIEW

**Comment by ddumitre456** [comment]
Ideally we 

> Changes look fine to me.
> 
> Do any customers use the mistral_postgresql plugin? If so, then perhaps we need another issue to get that building again?

At the moment we don't have customers for the postresql plugin. 

Ideally we want to compile the postresql plugin as well so that we keep postgresql in our list of plugin packages.

This is the error I get on CentOS 64-bit build machine (10.33.0.104):
```
gcc -o mistral_postgresql.x86_64 ../../common/plugin_control.o mistral_postgresql.o \
		-Wl,-Bstatic  -lpq -lldap_r-2 -llber-2 -luuid -lssl -lcrypto -lk5crypto -Wl,-Bdynamic   -lpthread -lgssapi_krb5 -lkrb5 -lcom_err -ldl -lz -lkrb5support -lkeyutils -lresolv -lsasl2 -lselinux -lsepol -lgcc_s
/usr/bin/ld: cannot find -lsasl2

```
`sasl2` is present on the machine:

```
$ pwd
/usr/lib64
$ ls -la *sasl2*
lrwxrwxrwx 1 root root     18 Jan  6 17:23 libsasl2.so.2 -> libsasl2.so.2.0.22
-rwxr-xr-x 1 root root 105464 Sep  3  2012 libsasl2.so.2.0.22
$ echo $LD_LIBRARY_PATH
/usr/lib64:/usr/local/gcc-8.2.0/lib64:
$ more /etc/ld.so.conf.d/lib64.conf
/usr/lib64
```

On CentOS 32-bit build machine (10.33.0.103) there is no `sasl2` library installed.

**Comment by RichardSJordan** [comment]
> sasl2 is present on the machine:

I think that `ld` will be looking for `libsasl2.so`. Very often there's a symlink from that name to the one with the version number in the file name. 

I suspect that creating a symlink from libsasl2.so -> libsasl2.so.2 would probably make that work. (Though obviously that wouldn't work for the 32-bit build machine.)

**Comment by ddumitre456** [comment]
I added back PostgreSQL plugin. It compiles now on both 32-bit and 64-bit machines.

There is still a problem. The problem is that on 32-bit machine some libraries are liked dynamically and they should be linked statically: 

```
gcc -o mistral_elasticsearch.i386 ../../common/plugin_control.o mistral_elasticsearch.o \
		-Wl,-Bstatic  /usr/local/lib/libcurl.a -L/usr/kerberos/lib -lldap -lkrb5support -lkeyutils -lssl -lcrypto -lz -Wl,-Bdynamic  -L/usr/kerberos/lib -ldl -lrt  -lldap-2 -lpthread -llber-2 -lgssapi_krb5 -lcom_err -lk5crypto -lresolv -lsasl2 -lselinux -lsepol -lgcc_s

```

` ldap-2`, `lber-2`, `gssapi_krb5`, `k5crypto`, `sasl2` should be linked statically.

**Comment by liamellexus** [comment]
I wouldn't be too worried about that, the use of 32-bit plugins is likely
to be 0. I'm happy for you to create an issue about that and leave it out
of this pull request if it's tricky to solve.

Liam

**Comment by ddumitre456** [comment]
I have created a new issue: #94.

**Pull request merged**
